allowBuilds:
  better-sqlite3: set this to true or false
  esbuild: set this to true or false
  unrs-resolver: set this to true or false
minimumReleaseAgeExclude:
  - '@biomejs/biome@2.5.11'
  - '@biomejs/cli-darwin-arm64@2.5.11'
  - '@biomejs/cli-darwin-x64@2.5.11'
  - '@biomejs/cli-linux-arm64-musl@2.5.11'
  - '@biomejs/cli-linux-arm64@2.5.11'
  - '@biomejs/cli-linux-x64-musl@2.5.11'
  - '@biomejs/cli-linux-x64@2.5.11'
  - '@biomejs/cli-win32-arm64@2.5.11'
  - '@biomejs/cli-win32-x64@2.5.11'
